[package]
name = "itehaas"
version = "0.1.0"
edition = "2021"
description = "Itehaas VCS engine"
license = "MIT"

[[bin]]
name = "itehaas"
path = "src/main.rs"

[dependencies]
clap = { version = "4.5", features = ["derive"] }
sha2 = "0.10"
hex = "0.4"
flate2 = "1.0"
anyhow = "1.0"
thiserror = "2.0"
tempfile = "3.10"

[dev-dependencies]
tempfile = "3.10"

[lib]
name = "itehaas_lib"
path = "src/lib.rs"
